name: 创建干净且完整的发行包

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    tags: # 当推送以 'v' 开头的标签时，自动触发
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    # 给权限！解决 403 错误
    permissions:
      contents: write

    steps:
      # 检出代码（包含子模块）
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          submodules: true # [关键] 这行确保你的 .gitmodules 引用的模块也被拉取

      # 安装依赖 (如果你使用 Node.js / Python / .NET 等)
      - name: 安装模块依赖
        run: |
          # 如果是 Node.js 项目，取消下一行注释
          # npm ci

          # 如果是 Python 项目，取消下一行注释
          # pip install -r requirements.txt

      # 安装 CRLF 转换工具（修复批处理闪退）
      - name: 安装 dos2unix 修复 bat 换行符
        run: sudo apt install dos2unix -y

      # 把所有 .bat 转换成 Windows CRLF 格式（关键！）
      - name: 修复批处理文件换行符
        run: find . -name "*.bat" -exec dos2unix {} \;

      # 清理并打包
      - name: 生成纯净压缩包
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "JX3Toolkit-${{ github.ref_name }}.zip" # 生成的压缩包名称
          # [关键] 排除列表：写上所有你不想要的东西
          exclusions: |
            *.git*
            *.github*
            *.vscode*
            *.code-workspace
            node_modules/*     # 排除本地依赖，将其视为构建环境文件
            __pycache__
            .gitignore
            .gitmodules
            README.md

      # 4. 将打包好的 zip 上传到 Release 页面
      - name: 发布到 GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: JX3Toolkit-${{ github.ref_name }}.zip
